/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_taxiao_cn_apple_jni_NativeMainJNI.h"
#include <iostream>
#include <stdio.h>
/* Header for class com_taxiao_cn_apple_jni_NativeMainJNI */
using namespace std;

/*
 * Class:     com_taxiao_cn_apple_jni_NativeMainJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_taxiao_cn_apple_jni_NativeMainJNI_sayHello(JNIEnv * env, jobject obj)
{

	cout<< "Hello from C++ sayHello " <<endl;
}

/*
 * Class:     com_taxiao_cn_apple_jni_NativeMainJNI
 * Method:    start
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_taxiao_cn_apple_jni_NativeMainJNI_start(JNIEnv * env, jobject obj, jstring function, jstring str)
{
  
	cout<< "Hello from C++ start " <<endl;
}
  

