/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taxiao_cn_apple_jni_NativeMainJNI */

#ifndef _Included_com_taxiao_cn_apple_jni_NativeMainJNI
#define _Included_com_taxiao_cn_apple_jni_NativeMainJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taxiao_cn_apple_jni_NativeMainJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_taxiao_cn_apple_jni_NativeMainJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_taxiao_cn_apple_jni_NativeMainJNI
 * Method:    start
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_taxiao_cn_apple_jni_NativeMainJNI_start
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
